### ISSUE TITLE
People are using The handicap as a winning

### ISSUE THREAD

**Issue by changcheng967** [changchengdouletmedia/OGS-Doulet-Media#14]
They play some stone and then count stones, they will win

**Comment by changcheng967** [comment]
[example](https://online-go.com/game/66972902)

**Comment by changchengdouletmedia** [comment]
Might be fixed

**Comment by changchengdouletmedia** [comment]
#15

**Comment by changchengdouletmedia** [comment]
15 maybe fixed

**Comment by DouletMedia** [comment]
#18 I did it, might need to edit the chat

**Comment by changchengdouletmedia** [comment]
done

**Comment by changchengdouletmedia** [comment]
did not change the other language @DouletMedia

**Comment by DouletMedia** [comment]
maybe do it later

**Comment by DouletMedia** [comment]
@changchengdouletmedia

**Comment by DouletMedia** [comment]
let @changcheng967 do it if he knows

**Comment by changcheng967** [comment]
> let @changcheng967 do it if he knows

nah

**Comment by changcheng967** [comment]
The [#114 in kata_speed](https://github.com/changcheng967/Kata_speed/pull/114) fixed the issue

**Comment by DouletMedia** [comment]
The [#114 in kata_speed](https://github.com/changcheng967/Kata_speed/pull/114) only changed English

**Comment by DouletMedia** [comment]
need more

**Comment by changcheng967** [comment]
[#118](https://github.com/changcheng967/Kata_speed/pull/118)

**Comment by changcheng967** [comment]
ok

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: changchengdouletmedia ***@***.***>
发送时间: Thursday, August 22, 2024 8:15:54 PM
收件人: changchengdouletmedia/OGS-Doulet-Media ***@***.***>
抄送: Cheng Chang ***@***.***>; Author ***@***.***>
主题: Re: [changchengdouletmedia/OGS-Doulet-Media] People are using The handicap as a winning (Issue #14)


Might be fixed

―

**Comment by changcheng967** [comment]
in computer go server, you need to cancel that
