### ISSUE TITLE
WHen the end the bto gonna win, it will lower visit under the max

### ISSUE THREAD

**Issue by changchengdouletmedia** [changchengdouletmedia/OGS-Doulet-Media#6]
WHen the end the bto gonna win, it will lower visit under the max

_Originally posted by @changcheng22023 in https://github.com/changchengdouletmedia/OGS-Doulet-Media/discussions/4#discussioncomment-10369004_

**Comment by changchengdouletmedia** [comment]
might be it's issue?

**Comment by changcheng22023** [comment]
I don't think so
